title: Maleficarum
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
# logo: "/img/maleficarum_logo.webp"
color_scheme: dark
# encoding: UTF-8
  
# url: https://just-the-docs.github.io

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  Maleficarum Blog: https://maleficarum.bearblog.dev/

footer_content: "Maleficarum is developed by Jens Hoenscheid"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
